version: '3'

services:
  frontend:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/your-database-name
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
